@startuml elevator simulation
class elevator {
  -int currentFloor
  -int destinationFloor
  -int direction
  -int doorStatus
  -int doorTimer
  -int doorTimerMax
  -int doorTimerMin
  -int doorTimerStep
  -int doorTimerStepMax
  -int doorTimerStepMin
  -int capacity
}

class person {
  -int currentFloor
  -int destinationFloor
  -int direction
}

class floor {
  -int floorNumber
  -int floorButton
  -int floorButtonStatus
  -int floorButtonTimer
  -int floorButtonTimerMax
  -int floorButtonTimerMin
  -int floorButtonTimerStep
  -int floorButtonTimerStepMax
  -int floorButtonTimerStepMin
}

class elevatorController {
  -int currentFloor
  -int destinationFloor
  -int direction
  -int doorStatus
  -int doorTimer
  -int doorTimerMax
  -int doorTimerMin
  -int doorTimerStep
  -int doorTimerStepMax
  -int doorTimerStepMin
  -int floorNumber
  -int floorButton
  -int floorButtonStatus
  -int floorButtonTimer
  -int floorButtonTimerMax
  -int floorButtonTimerMin
  -int floorButtonTimerStep
  -int floorButtonTimerStepMax
  -int floorButtonTimerStepMin
}

elevatorController --> elevator
elevatorController --> floor
elevatorController --> person

elevator --> floor
elevator --> person

floor --> person


@enduml
